name: VIL
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fab_circular_menu: ^0.1.4
  flutter_dialogflow: ^0.1.2
  photo_view: ^0.5.0
  charts_flutter:
  fancy_bottom_navigation: ^0.3.2
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.4
  provider: ^4.0.3
  carousel_slider: ^1.4.1
  fluttertoast: ^3.1.3
  firebase_messaging: ^6.0.9
  font_awesome_flutter:
  flip_card:



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - images/bad.png
    - images/cpp.png
    - images/good.png
    - images/java.png
    - images/js.png
    - images/linux.png
    - images/py.png
    - images/success.png
    - assets/BotDialog.json
    - assets/images/img_not_available.jpeg
    - assets/images/mimi1.gif
    - assets/images/mimi2.gif
    - assets/images/mimi3.gif
    - assets/images/mimi4.gif
    - assets/images/mimi5.gif
    - assets/images/mimi6.gif
    - assets/images/mimi7.gif
    - assets/images/mimi8.gif
    - assets/images/mimi9.gif
    - assets/LoginImages/image_01.png
    - assets/LoginImages/image_02.png
    - assets/LoginImages/logo.png
    - assets/smps.png
    - assets/seagate_hard_disk.png
    - assets/breadboard.png
    - assets/sata_cabels.png
    - assets/bottom_nav_bar/bag_icon.png
    - assets/bottom_nav_bar/home_icon.png
    - assets/bottom_nav_bar/search_icon.png
    - assets/kc_temp.jpg
    - assets/xchanger_logo.png
    - assets/LoginImages/image_01.png
    - assets/LoginImages/image_02.png
    - assets/LoginImages/logo.png
    - assets/WalletImages/bg.jpg
    - assets/WalletImages/bg1.jpg
    - assets/WalletImages/users/anna.jpeg
    - assets/WalletImages/users/gillian.jpeg
    - assets/WalletImages/users/judith.jpeg
    - assets/visa.png
    - assets/leaderboard.png
    - assets/foodIcon.png
    - assets/shoppingCart.png
    - assets/healthCare.png
    - assets/travel.png
    - assets/working.png
    - assets/gaming.png
    - assets/banking.png
    - assets/quiz.jpg
    - assets/cricket.jpeg
    - assets/hospital.jpeg
    - assets/shoppingGame.png
    - assets/fruitNinja.png
    - assets/findthehidden.png
    - assets/pow.png
    - assets/bankingJunior.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Noto
  #     fonts:
  #       - asset: fonts/NotoSansHK-Regular.otf

  #   - family: OpenSans
  #     fonts:
  #       - asset: fonts/OpenSans-SemiBold.ttf

  #   - family: Quando
  #     fonts:
  #       - asset: fonts/Quando.ttf
  #   - family: Satisfy
  #     fonts:
  #       - asset: fonts/Satisfy.ttf
  #   - family: Alike
  #     fonts:
  #       - asset: fonts/Alike-Regular.ttf
  #   - family: Quicksand
  #     fonts:
  #       - asset: fonts/Quicksand-Bold.ttf
  #       - asset: fonts/Quicksand-Light.ttf
  #       - asset: fonts/Quicksand-Medium.ttf
  #       - asset: fonts/Quicksand-Regular.ttf
  #       - asset: fonts/Quicksand-SemiBold.ttf
  #   - family: Avenir
  #     fonts:
  #       - asset: assets/Fonts/Avenir-Book.ttf
  #       - asset: assets/Fonts/Avenir-Heavy.ttf
  #         weight: 700
  #       - asset: assets/Fonts/Avenir-Light.ttf
  #         weight: 300
  #       - asset: assets/Fonts/Avenir-Medium.ttf
  #         weight: 500
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/Fonts/RobotoMono-Regular.ttf
        
        
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
